apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: fairness-python
  namespace: default
spec:
  runLatest:
    configuration:
      build:
        apiVersion: build.knative.dev/v1alpha1
        kind: Build
        spec:
          serviceAccountName: build-bot
          source:
            git:
              url: https://github.com/Tomcli/ffdl-knative
              revision: master
          template:
            name: kaniko
            arguments:
            - name: IMAGE
              value: docker.io/tomcli/fairness-knative
            - name: DOCKERFILE
              value: ./Dockerfile-fairness
      revisionTemplate:
        spec:
          containerConcurrency: 0
          container:
            image: docker.io/tomcli/fairness-knative
