apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: fairnessevents-subscription
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: pipelinechannel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: fairness-python
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: robustnessevents-subscription
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: pipelinechannel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: robustness-python
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: authcontrollerevents-subscription
spec:
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: pipelinechannel
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: authentication-controller
---
